-- Banco de dados: `Projeto`
--

--

--
-- Estrutura da tabela `CLIENTES`
--

CREATE TABLE `CLIENTES` (
  `IDCLI` int(5) NOT NULL,
  `TIPOID` int(5) NOT NULL,
  `NOMECLI` varchar(255) NOT NULL,
  `CLICEP` varchar(8) NOT NULL,
  `CLIRUA` varchar(255) NOT NULL,
  `CLIBAIRRO` varchar(255) NOT NULL,
  `CLICIDA` varchar(255) NOT NULL,
  `CLIESTA` varchar(255) NOT NULL,
  `CLIENDE` varchar(255) NOT NULL
)

--
-- Índices para tabela `CLIENTES`
--
ALTER TABLE `CLIENTES`
  ADD PRIMARY KEY (`IDCLI`),
  ADD KEY `FK_TIPOPESSOA` (`TIPOID`);

--
-- AUTO_INCREMENT de tabela `CLIENTES`
--
ALTER TABLE `CLIENTES`
  MODIFY `IDCLI` int(5) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=23;

ALTER TABLE `CLIENTES`
  ADD CONSTRAINT `FK_TIPOPESSOA` FOREIGN KEY (`TIPOID`) REFERENCES `TIPO_PESSOA` (`TIPOID`) ON DELETE CASCADE ON UPDATE CASCADE;



-- TABELA TIPO_PESSOA

-- Estrutura da tabela `TIPO_PESSOA`
CREATE TABLE `TIPO_PESSOA` (
  `TIPOID` int(5) NOT NULL,
  `TIPODESC` varchar(30) NOT NULL
);

ALTER TABLE `TIPO_PESSOA`
  ADD PRIMARY KEY (`TIPOID`)

ALTER TABLE `TIPO_PESSOA`
  MODIFY `TIPOID` int(5) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=124;

